theme: jekyll-theme-slate
title: Welcome to <a href="/">OmniFact.org</a>
description: Misinformation is circulating on social media. As technologists, we need to stand up for truth.
plugins:
  - jemoji
